### ISSUE TITLE
[UI - Bug] I broke the Squad Stuff & Squad L icons :(

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#10]
oops

**Comment by samuelgrant** [comment]
I'll take a look

**Comment by samuelgrant** [comment]
This is related to a different naming scheme in FA5.

@Makeshift look here: https://fontawesome.com/icons for icons that you like and I can make it happen. 
Hint: I have FA5 pro.

**Comment by samuelgrant** [comment]
Icons are repaired in [pull request 11](https://github.com/Makeshift/eve-goons-waitlist/pull/11).

Issue has been resolved by replacing FA4 with FA5 and updating class names. The dropdown menus on the side nav bar had class options from @Makeshift  that caused icons not to render, these classes have been removed restoring the icons.

**Comment by samuelgrant** [comment]
I want to do an overhaul of icons later for continuity reasons. But this is low on the list of tasks to do. For now, they work so I will close this issue.
