### ISSUE TITLE
[Query] Possible redundant code.

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#104]
@Makeshift  what is the point of this code, was it for error notifications/user feedback on the index page? If so, can I remove it with the introduction of user feedback alerts introduced in pull #100 

https://github.com/Makeshift/eve-goons-waitlist/blob/349c6168aeed995d1c88ea697ff44debbe1fdfca/views/waitlist.njk#L241-L251

**Comment by Makeshift** [comment]
Literally the whole waitlist is redundant code.

But yes this can be removed, it was for alerts.

**Comment by samuelgrant** [comment]
I'll remove it with my next pull request

**Comment by samuelgrant** [comment]
This will be resolved by pull request #106
