### ISSUE TITLE
[Question] Testing Framework?

### ISSUE THREAD

**Issue by mlohstroh** [Makeshift/eve-goons-waitlist#113]
Not sure where else to ask this, but, what would you guys think about a testing framework like [Jest](https://facebook.github.io/jest/docs/en/getting-started.html)? 

For someone like me who probably doesn't know all the pitfalls of this application, it'd be a bit nicer for me to feel confident that I didn't break something else later on. Also, would could make a quick Travis config to run it on all PR's.

**Comment by samuelgrant** [comment]
I wouldn't have any issues with unit testing

**Comment by Makeshift** [comment]
I'd be up for it - I've never had a project big enough to use a testing framework so I've never learned to use one.  If you feel like setting it up and giving us a quick rundown on how to use your specific configuration (unless it's pretty generic) I'd happily work it into my process.

**Comment by samuelgrant** [comment]
@Makeshift There is some code on github now for some tests of the scheduler. I'm going to sit down at some point this week and get a handle on unit testing within JS and then I'm happy to go over it with you at a time that suits if you would like a run down.

**Comment by mlohstroh** [comment]
Closing as I have added the jest framework into Sam's branch.
