### ISSUE TITLE
[BUG] Join/Queue panels are visible when there are no fleets

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#20]
### Bug Description
The join the waitlist, and the queue info panels are visible where there are no active fleets. We can look at putting something there but for now it should just be the 'Waitlist Inactive' banner and any FC banner message that is currently being used for the alpha notice.

### Reproduction Steps
Close any open fleets and go to the `/` route.

### Expected Outcome
Remove pilot panels on the left.

#### Notes
We could look at putting some cool things in there long term. Maybe focus stats during an active deployment, and in between deployment focus information while we are waiting for a spawn. Just a thought.

**Comment by samuelgrant** [comment]
Also, I wonder if Queue panel should be hidden if a pilot is not on the waitlist.

**Comment by Makeshift** [comment]
I'm calling this one a bug because I already tried to fix it before and failed :P

**Comment by samuelgrant** [comment]
This has been resolved by merge #42
