### ISSUE TITLE
Something something alt section

### ISSUE THREAD

**Issue by Viscart** [Makeshift/eve-goons-waitlist#29]
### Bug Description
Clicking on "Remove all alts" queued me up.

### Reproduction Steps
Click on "Remove all alts" and watch.

### Expected Outcome
"Remove all alts" working.

### Actual Outcome
"Remove all alts" not working.

#### Notes
grr

**Comment by samuelgrant** [comment]
This 'alts' panel on the waitlist page is not use-able yet. It **will** let you manage what alts you want to get into a fleet on a given day.

I will put a quick fix together to stop it from doing things today as a stop gap measure until makeshift can get alts working.

**Comment by Makeshift** [comment]
I apparently forgot to remove that button. I don't have proper alt support yet. My bad.

**Comment by samuelgrant** [comment]
The alt character waitlist up panel has been hidden for now. It will be made visible once we have the planned alt system working.

I am going to close this issue now.
