### ISSUE TITLE
[Feature request] Pilot's language indicator 

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#3]
Give the FC an indicator of what language a pilot speaks so we have an idea who might need a translator.

**Comment by Makeshift** [comment]
Dropdown + tickbox to let the FC know they may need a translator sounds good.

**Comment by Makeshift** [comment]
Debating removing this because it turns out nobody knows how to read anyway.

**Comment by samuelgrant** [comment]
Let's do it

**Comment by samuelgrant** [comment]
Once issue #59  is completed this feature has been removed.
