### ISSUE TITLE
"Fleet at a glance" view extends past the view of the monitor

### ISSUE THREAD

**Issue by 1285done** [Makeshift/eve-goons-waitlist#30]
### Bug Description
http://img.scassany.space/AXqBy8Ne.png

### Reproduction Steps
make a fleet, add some people to it, look at the fleet at a glance

### Expected Outcome
It doesn't look like shit

### Actual Outcome
It looks like shit

#### Notes

**Comment by samuelgrant** [comment]
So, breaking this up into four columns is probably a @Makeshift thing. In the meantime, can I get these ships sorted in order of most to least?

**Comment by Makeshift** [comment]
```
if (i % 3 === 0) {
 table += "</tr><tr>"
}
```

**Comment by Makeshift** [comment]
Fixed
