### ISSUE TITLE
People aren't being cleared from the waitlist.

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#32]
### Bug Description
When an invite is sent they get highlighted and then stay there. They are not removed from the waitlist

#### Notes

**Comment by Makeshift** [comment]
Does that happen for all users or is it occasional? I'm curious if the name is being parsed incorrectly.

**Comment by samuelgrant** [comment]
I haven't been able to test it as the waitlist died, but it only happened to a few people. I believe they never got successful invites.

**Comment by samuelgrant** [comment]
Issue #41 covers this,
