### ISSUE TITLE
FC Waitlist order messing itself up

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#33]
Waitlist will occasionally mess with the order of waitlistee's due to mongo.

Fix: Have them return in order of when they signed up.

**Comment by samuelgrant** [comment]
Can this same time be used to display a wait time for FCs?

**Comment by Makeshift** [comment]
Yup, will do that at the same time

**Comment by samuelgrant** [comment]
@Makeshift I believe believe both issues have been resolved, is that correct?

**Comment by Makeshift** [comment]
Keep it up for now, the 'fix' for this was a quick hack that broke locations, so I need to do this properly

**Comment by lethern** [comment]
Tried to fix this, available on the /test/commander

**Comment by Makeshift** [comment]
The waitlist itself is in the correct order, I fixed that a while ago (at the expense of location), but lethern has made the ship types order/sort too.

**Comment by lethern** [comment]
> (at the expense of location)
fixed this thing (tried to)

**Comment by lethern** [comment]
What was wrong previously:
```
function contWaitlistGenerate
	(...)
	for (var i = 0; i < usersNeeded; i++) {
		(...)
		users.getLocation(usersOnWaitlist[i].user, function () {   // X
			(...)
			waitlistHTML +=
```
that was the old code that caused out-of-order, because the function (marked X) might have been callback-ed in any order, calling `waitlistHTML +=` in any order.
Fix: take the `waitlistHTML +=` out of callback-hell

**Comment by samuelgrant** [comment]
This is a non-issue now.
