### ISSUE TITLE
Do proper logging

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#35]
- [ ] WITH COLORS
- [ ] AND DIFFERENT OUTPUT TYPES (info, error, debug etc.)
- [ ] NOT IN STUPID PLACES
- [ ] TO A FILE! (I know this is revolutionary)

**Comment by samuelgrant** [comment]
@Makeshift Other than checking our functions to make sure we log things correctly, is there anything else you are looking for?

**Comment by samuelgrant** [comment]
```(2:18:45 AM) makeshift_storque: Technically that's complete I guess
(2:18:46 AM) makeshift_storque: But we do need moar```
