### ISSUE TITLE
If you press the make fleet button without a crest link, it dies. Horribly.

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#36]
Fix that.

**Comment by samuelgrant** [comment]
Don't want to risk pressing it, but doesn't the field have the 'required' attribute?

**Comment by samuelgrant** [comment]
The input forum doesn't require an input. I will address this today. However, we still need back end validation that a valid esi link exists.

**Comment by Makeshift** [comment]
Closing this because the other bug report is better.
