### ISSUE TITLE
selecting stuff

### ISSUE THREAD

**Issue by SirNardieu** [Makeshift/eve-goons-waitlist#38]
### Bug Description
cant select/copy any text

### Reproduction Steps
try to select/copy some text

### Expected Outcome
text gets selected and then copied

### Actual Outcome
nothing gets selected

#### Notes

**Comment by samuelgrant** [comment]
Working on it.

Basically, I wanted to keep certain things from being highlighted where it isn't needed. Mainly images and the public wait-list page. I can fix this by adjusting what items have the ::noselector elements.

It will be done today.

**Comment by samuelgrant** [comment]
Need to make a change to the css file for this to actually work.

**Comment by samuelgrant** [comment]
Okay the CSS update looks like it works. Please open a new ticket with a link to this one if the issue needs to be readdressed.
