### ISSUE TITLE
Connection Partially Encrypted

### ISSUE THREAD

**Issue by Zrubi** [Makeshift/eve-goons-waitlist#39]
### Bug Description
At least one external URL "breaking" the SSL encryption:
image.eveonline.com

### Expected Outcome
Should be called by https://

**Comment by samuelgrant** [comment]
I'm on it. This is being caused by the avatar icon on the nav bar.

**Comment by samuelgrant** [comment]
Fix deployed, you won't notice a change this incursion.

**Comment by samuelgrant** [comment]
Okay I am now doing this in a more awesome way - see the above commit. This will solve it now.
