### ISSUE TITLE
Invite Status Indicators

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#41]
### Bug Description
When inviting a user their row is highlighted green. If the invite succeeds they are removed from the database and view. If the invite fails, they stay highlighted green. This persists through page refreshes. 

### Reproduction Steps
Invite a player who is offline, in another fleet or who rejects the invite.

### Expected Outcome
Clicking the invite button makes the users row go blue. After the invite is sent through ESI successfully the database record should  be deleted and for the FC who pressed the invite button the row should go green for 10 seconds before it is deleted. 

If the invite fails, the row should go red (only for the FC who clicked invite) and it should not persist past a page refresh.

#### Notes

Color classes: 
- invite-pending (when a user clicks invite; this class should be used pending a sent or failed response)
- invite-sent (if ESI accepts the fleet invite request - this does not mean the user accepted the invite, just that they received an invite).
- invite-failed (Invite failed (The pilot did not get sent an invite) - could be due to the user being offline, in a fleet, fleet being full)

**Comment by Makeshift** [comment]
Can confirm I'm bad.

**Comment by samuelgrant** [comment]
Works.
