### ISSUE TITLE
Unexpectedly long wait time

### ISSUE THREAD

**Issue by Jason-Theta** [Makeshift/eve-goons-waitlist#43]
### Bug Description
There is too long between queuing for fleet and being accepted to fleet

### Reproduction Steps
Queue for fleet

### Expected Outcome
It doesn't take ages

### Actual Outcome
It takes ages

#### Notes
Blame samuel for this

**Comment by samuelgrant** [comment]
Always wanted to use that label.

**Comment by Makeshift** [comment]
I knew it would be useful.
