### ISSUE TITLE
unfuck this please

### ISSUE THREAD

**Issue by 1285done** [Makeshift/eve-goons-waitlist#46]
### Bug Description
A shiptype name that is too long really fucks up the waitlist

### Reproduction Steps
Put a name like "megamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamegamega"

### Expected Outcome
It doesn't look like shit

### Actual Outcome
It looks like shit

#### Notes
I'm gay

**Comment by Makeshift** [comment]
Fixing this won't be necessary as ship names will be dictated by EFT blocks(Well, hopefully by the ESI active ship fit endpoint if it ever gets released) and validated serverside in the future, but I'll keep this open for now.

**Comment by Makeshift** [comment]
@samuelgrant It would make Scassany happy, I'm sure.

**Comment by samuelgrant** [comment]
Okay well, this incursion won't last much longer. The trick question is, when do you see yourself putting in a proper alt/fit system? 

_It doesn't have to be the perfect when we get the endpoint we've asked for system_

**Comment by Makeshift** [comment]
#whenIcanbebothered

**Comment by samuelgrant** [comment]
#mailspam also this incursion wont be up much longer. I can't be bothered adding two words to limit characters in the input field.

**Comment by Makeshift** [comment]
I feel you, brother.

**Comment by samuelgrant** [comment]
That was my issue to close,  FOOL

**Comment by samuelgrant** [comment]
Oh wow, I am so shit I thought this was another issue. ... Never mind :D
