### ISSUE TITLE
[UI-Bug] Resize issue on Ban/Whitelist/New FC forums

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#5]
If screens shrink too far the input fields become too small. @samuelgrant needs to investigate an alternative layout

**Comment by samuelgrant** [comment]
Found a solution for the input forums on the following views templates [in pull request 6](https://github.com/Makeshift/eve-goons-waitlist/pull/6)
- Ban
- White-list
- FC Management
- Fleet Directory

This should resolve fields becoming squashed as the screen shrinks. Vertical forum fields will be used

**Comment by Makeshift** [comment]
Does #6 solve this?

**Comment by samuelgrant** [comment]
Working on it from my end. Need to make some changes that I will then push to git. 

Depending on how long it will take you to sort out the templates I can either wait or do it tomorrow and make another pull request.

**Comment by Makeshift** [comment]
Templates likely won't get done today - I have secret santa presents to grind for. If you fancy doing it today/tomorrow that's fine, or I can merge changes later.

**Comment by samuelgrant** [comment]
This issue should now be resolved with [git pull 7](https://github.com/Makeshift/eve-goons-waitlist/pull/7).
