### ISSUE TITLE
[Feature] Invite to squad, Fleet Comp

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#52]
## Description
It would be nice to allow the waitlist to invite people to a specific squad rather than the default squad. What we should do is replace the green plus button with a drop-down nav button. Then list each squad in say wing one and allow fcs to click on the squad they want to put the person in. 

At the same time the fleet comp should  only show people in the 'active wing'. That way I don't see scouts/cynos that are in fleet in that comp window. 

## Usecase
- Arsefleet legions are both DPS and Logi ships. This means the fleet at a glance tab won't help. Having a logi squad vs a dps squad could allow the FC to get a better view of how many legions are logi vs dps.
- Being able to add people into separate squads minimizes the risk of a squad commander accidentally warping the entire fleet off grid.
- People will end up in the expected squads rather than the one ESI puts them in.
- If FCs max squads at 14 people + the squad commander, squad commanders could add their squads to their watchlists as a form of AFK checking pilots.

**Comment by Makeshift** [comment]
Can you mock up a dropdown for this? 
I might even be able to automate squad creation/naming along with MOTD generation, and do invites straight into the correct squads.

**Comment by samuelgrant** [comment]
WIP - The next commit should contain the code to complete this ticket. 

Squad names are pulled on each page refresh, and FCs must choose a squad to invite each pilot to.
