### ISSUE TITLE
A real templating engine

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#55]
Okay, good job, you made your own shitty templating engine. Now got and get a real one.

**Comment by Lucius-Q-User** [comment]
May i direct your attention here https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by Makeshift** [comment]
Having just looked at all the available templating engines, meh.

**Comment by samuelgrant** [comment]
I still have [a single view](https://github.com/Makeshift/eve-goons-waitlist/blob/master/pageContent/fcFleetManage.js) using the old system. This is being resolved on my personal dev branch and should be pushed today.

As there is a new issue opened (#89) regarding tidying up the template files, I've closed this ticket.
