### ISSUE TITLE
Change "Login with Eve Online" to use the official Eve CDN

### ISSUE THREAD

**Issue by Makeshift** [Makeshift/eve-goons-waitlist#56]
https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/intro.html

The Eve CDN has actually been updated to have the login images so we should use those.

**Comment by samuelgrant** [comment]
Okay, will look at this today

**Comment by samuelgrant** [comment]
After discussing this with @Makeshift, we have opted to keep the image locally. This image was downloaded from the CDN. This was done for two reasons:

- If our site is down we don't need the image anyway, if their server goes down then we lose our link to the image.
- If their HTTPS connection becomes invalid then visitors to our site won't get a nice secured sign in browsers.

Bonus reason: page load time is not affected by another site.
