### ISSUE TITLE
Not a bug: Red border on the input fields confuses new people

### ISSUE THREAD

**Issue by oititov** [Makeshift/eve-goons-waitlist#65]
#### Notes

There is no bug, there is a slight design problem. The style Samuel created is great, but it has a small issue. The red border on the active input text field confuses new people to think that the page does not like what they're typing. I'd recommend changing this color to something more neutral.

**Comment by Makeshift** [comment]
It's actually a template I totally stole and made him modify

**Comment by samuelgrant** [comment]
Quote "I hate HTML, I'm SHIT"
Quote "I Don't know what I'm doing"
Quote "Do it for me, I am bad"

Okay maybe not a quote, but close enough.

**Comment by samuelgrant** [comment]
@oititov Just saw this ticket. I've put it on my list of things to look at.

No promises.
