### ISSUE TITLE
[Feature] Calculate CSPA charge.

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#78]
Calculate CSPA charge when the user joins the waitlist. Alert them to a CSPA charge if they have one, and that it will prevent them from joining the fleet.
`POST/characters/{character_id}/cspa/`

**Comment by Makeshift** [comment]
Nah. Just catch the error when we try and do anything with fleets. Same with when they're offline.

**Comment by Makeshift** [comment]
PUNISH THEM FOR THEIR CRAPPY SETTINGS

**Comment by samuelgrant** [comment]
Agreed.
