### ISSUE TITLE
[UI - Feature] Bootstrap tooltips & FA5

### ISSUE THREAD

**Issue by samuelgrant** [Makeshift/eve-goons-waitlist#8]
@Makeshift please replace the font awesome four CDN (CSS File) with the font awesome five `<script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>` script.

Bootstrap tool-tips also needs to be [bootstrap documentation](https://v4-alpha.getbootstrap.com/components/tooltips/).

**Comment by samuelgrant** [comment]
I am happy to do both of those things once the templating has been completed.

**Comment by Makeshift** [comment]
Having never used `defer` before, I put it in the header and am kinda hoping it works?
I put the tooltip enabling in the footer in the hope that everything will have loaded before it runs. I also added the CDN for the tooltip JS in the header. I apparently don't need to add the CSS so I didn't.

I don't think we have any tooltips right now so I can't test.

Will keep open till confirmed.

**Comment by samuelgrant** [comment]
Tooltips are there on Leadership pages at the moment. But they will need tweaking depending on how you build the back-end. I will cone the repo shortly and check things on my end.

**Comment by samuelgrant** [comment]
Tooltips now function and will be added as needed. Thanks.
